# -*- coding: utf-8 -*-
"""Object Detection with Yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11SYowa9nmeP2NvRiVUvd8HCiq-gGCjDK
"""

!pip install ultralytics

from ultralytics import YOLO

DIR = '/content/drive/MyDrive/dataset/yolo/traffic-sign-detection'

model = YOLO('yolov8n.pt')

model.train(
    data = "/content/drive/MyDrive/dataset/yolo/traffic-sign-detection/data.yaml", # yaml dosyasinda veri yollari ve sinif isimleri tanimli
    epochs = 2, # egeitim dongu sayisi
    imgsz = 640, # gorsel boyutu
    batch = 16, # mini batch boyutu donanima bagli ayarlanir
    name = "traffic-sign-model", # output folder name
    lr0 = 0.01, # baslangicta ki ogrenme orani
    optimizer = "SGD", # optimizer alternatif ADAM
    weight_decay = 0.0005, # agirlik cezasi overfitting i engellemek icin
    momentum = 0.935, # SGD momentum
    patience = 50, # early stopping icin sabir suresi
    workers = 2, # data loader worker sayisi
    device = "cpu", #  cpu veya cuda
    save = True, # modelleri kaydet
    save_period = 1, # kac epoch da bir kayit yapilacagi
    val = True, # her epoch sonuncunda validasyon gerceklestilecek
    verbose = True, # egitim sureci terminale detayli bir sekilde yazilir
    )

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

model = YOLO('/content/runs/detect/traffic-sign-model2/weights/best.pt')

image_path = '/content/drive/MyDrive/dataset/yolo/traffic-sign-detection/test/images/ezgif-2-2289282d6c_jpg.rf.62b4bdbc48c5235299cfcc5682ed084b.jpg'
image = cv2.imread(image_path)

results = model(image_path)[0]
print(results)

for box in results.boxes:
  x1,y1,x2,y2 = map(int, box.xyxy[0])
  cls_id = int(box.cls[0])
  confidence = float(box.conf[0])
  label=f"{model.names[cls_id]} conf: {confidence:.2f}"

  cv2.putText(image, label, (x1,y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
  cv2.rectangle(image, (x1,y1), (x2,y2), (0,255,0), 2)

cv2_imshow(image)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.imwrite("output.jpg", image)